### ISSUE TITLE
Ditch Google Analytics

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/uavcan.org#29]
Our website [appears to be violating ePD](https://consent.guide/google-analytics-cookie-consent/) by installing tracking cookies without affirmative consent from the user.

Considering that:

1. A proper solution takes some resources to implement correctly.
2. Many customers from our user base would be likely to disable tracking cookies.
3. Many web-browsers nowadays do not send tracking cookies at all (mine doesn't and it's a regular browser).
4. The value of the collected intelligence is very low.
 
Keeping Google Analytics alive makes little sense.

@thirtytwobits fyi

**Comment by clyde-johnston** [comment]
Removed with commit [e27132](https://github.com/UAVCAN/uavcan.org/commit/e27132fd78adeef0d42d479e5776f9522cbb2428).
