### ISSUE TITLE
Link to legacy UAVCAN website is broken

### ISSUE THREAD

**Issue by antoinealb** [UAVCAN/uavcan.org#6]
When clicking the  Legacy v0 button on uavcan.org, which points to legacy.uavcan.org I am getting a 404 error.

It would be convenient to still have access to those docs, even if the focus is on the v1 at the moment.

**Comment by pavel-kirienko** [comment]
Thanks Antoine. We were migrating to the new front page so there was a temporary disruption. Should be good now.

**Comment by antoinealb** [comment]
Indeed, seems like it works now. Thanks.
