### ISSUE TITLE
List featured adopters on the front page

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/uavcan.org#7]
We are collecting the logos to be published on the front page in section "Featured adopters". Currently there are 9 entries so far.

**Comment by igalloway** [comment]
Hi Pavel - NXP is an adopter. We'd be happy to be listed.

**Comment by pavel-kirienko** [comment]
@igalloway this is wonderful and it helps us a lot. Is there a specific NXP webpage dedicated to UAVCAN where I should link the logo to, or should it be just nxp.com?

**Comment by aentinger** [comment]
Hi @pavel-kirienko :wave:
[LXRobotics](https://lxrobotics.com) is using UAVCAN within the [Viper Quadcopter Project](https://github.com/107-systems) and would also be happy to be listed.

![lxrobotics-logo](https://user-images.githubusercontent.com/3931733/87001393-9fa83b80-c1b7-11ea-98f9-440a1932843c.png)

**Comment by pavel-kirienko** [comment]
@aentinger please send us a pull request with your logo as shown here: https://github.com/UAVCAN/uavcan.org/tree/master/adopters. Thanks!

**Comment by aentinger** [comment]
Done in #10 :wink:
